-- MySQL Script generated by MySQL Workbench
-- dim. 16 sept. 2018 17:03:07 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;


-- -----------------------------------------------------
-- Table `blog`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`authors` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`billets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`billets` (
  `id_billet` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `date_create` DATETIME NULL,
  `title` TEXT NOT NULL,
  `authors_id_author` INT NOT NULL,
  PRIMARY KEY (`id_billet`, `authors_id_author`),
  INDEX `fk_billets_authors_idx` (`authors_id_author` ASC),
  CONSTRAINT `fk_billets_authors`
    FOREIGN KEY (`authors_id_author`)
    REFERENCES `blog`.`authors` (`id_author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`comments` (
  `id_comments` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `date_comment` DATETIME NULL,
  `billets_id_billet` INT NOT NULL,
  `billets_authors_id_author` INT NOT NULL,
  PRIMARY KEY (`id_comments`, `billets_id_billet`, `billets_authors_id_author`),
  INDEX `fk_comments_billets1_idx` (`billets_id_billet` ASC, `billets_authors_id_author` ASC),
  CONSTRAINT `fk_comments_billets1`
    FOREIGN KEY (`billets_id_billet` , `billets_authors_id_author`)
    REFERENCES `blog`.`billets` (`id_billet` , `authors_id_author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`thematique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`thematique` (
  `id_thematique` INT NOT NULL,
  `theme` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_thematique`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`thematique_has_billets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`thematique_has_billets` (
  `thematique_id_thematique` INT NOT NULL,
  `billets_id_billet` INT NOT NULL,
  `billets_authors_id_author` INT NOT NULL,
  PRIMARY KEY (`thematique_id_thematique`, `billets_id_billet`, `billets_authors_id_author`),
  INDEX `fk_thematique_has_billets_billets1_idx` (`billets_id_billet` ASC, `billets_authors_id_author` ASC),
  INDEX `fk_thematique_has_billets_thematique1_idx` (`thematique_id_thematique` ASC),
  CONSTRAINT `fk_thematique_has_billets_thematique1`
    FOREIGN KEY (`thematique_id_thematique`)
    REFERENCES `blog`.`thematique` (`id_thematique`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thematique_has_billets_billets1`
    FOREIGN KEY (`billets_id_billet` , `billets_authors_id_author`)
    REFERENCES `blog`.`billets` (`id_billet` , `authors_id_author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
